# ghoshell.llms.openai.OpenAIConfig
text_completions:
  default:
    model: text-davinci-003
    max_tokens: 512
    temperature: 0.7
    n: 1
chat_completions:
  default:
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 512
  turbo-16k:
    model: "gpt-3.5-turbo-16k"
    temperature: 0.3
    max_tokens: 3000
    timeout: 25
    request_timeout: 30